### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by rejsshdds** [undefined06855/EditorMusic#6] opened 2024-04-28 01:29 UTC
I crash every time I press paste state/press color or changing the z layer/orders on custom objects and glow objects
[Crash 2024-04-27 20.16.21.dmp](https://github.com/undefined06855/EditorMusic/files/15140445/Crash.2024-04-27.20.16.21.dmp)
[launcher_logcat.txt](https://github.com/undefined06855/EditorMusic/files/15140450/launcher_logcat.txt)

**Comment by undefined06855** [comment] 2024-04-28 10:03
this has the same root cause as #5 it seems

**Comment by undefined06855** [comment] 2024-04-28 10:47
could you send the logs in the geode folder/logs when your game crashed?

**Comment by rejsshdds** [comment] 2024-04-28 11:34
[Geode 2024-04-28 06.30.43.log](https://github.com/undefined06855/EditorMusic/files/15141943/Geode.2024-04-28.06.30.43.log)

**Comment by undefined06855** [comment] 2024-04-28 15:23
this should be fixed in 1.1.2

**Closed by undefined06855** 2024-04-28 15:23 UTC
Labels: bug
